### PR TITLE
Add the possibility to load multiple aws secret keys

### PR DESCRIPTION
**Pull request by ThiagoAnunciacao**
Hi, first of all, thank you this gem is what I'm looking for to setup the env's of our projects. 

We just need to chance a little bit, to make it work for multiple secret keys. I tried to change less that I can and keep your way to call our env name, to you didn't need any work or change in your code.

If you need more examples or explanation, let me know.

### CODE REVIEW

**Comment by ThiagoAnunciacao** [comment]
@iagopiimenta I made some improvements to make the code more simple and easy to read.

**Comment by iagopiimenta** [comment]
Hi @ThiagoAnunciacao!
First of all, thanks for contributing to the project.
I appreciate your changes. I would just like to request you fix the rubocop offenses [described at the CI](https://github.com/iagopiimenta/aws_secrets_loader/actions/runs/4670616392/jobs/8270569931).

**Comment by ThiagoAnunciacao** [comment]
Hi, thanks for your reply... I made some improvements fixing the rubocop offenses and letting just your ENV to setup the secret names.

**Comment by ThiagoAnunciacao** [comment]
You need that I run a rebase on this branch?

**Comment by iagopiimenta** [comment]
> You need that I run a rebase on this branch?

I had to adjust the GitHub workflow

**Pull request merged**
